---
# tasks file for jenkins
- name: "install gpg required by apt_key"
  apt:
    name: gnupg
    state: present

- name: "add jenkins key"
  apt_key:
    state: present
    url: "{{ jenkins_key_url }}"

- name: "add repository"
  apt_repository: 
    filename: "{{ jenkins_repo.name }}"
    repo: "{{ jenkins_repo.url }}"
    state: present
    update_cache: yes

- name: "Install Jenkins and Java"
  apt:
    name: "{{ item.value.name }}"
    state: present
  loop:
    "{{lookup('dict', packages) }}"

- name: "daemon-reload"
  systemd:
    daemon_reload: true
    
- name: "Starting jenkins" 
  service:
    name: "jenkins"
    state: started
    enabled: yes