---
# vars file for jenkins
java: "openjdk-11-jdk"

jenkins_repo:
  name: "jenkins"
  url: "deb https://pkg.jenkins.io/debian-stable binary/"
  description: "Jenkins repo"

packages:
  java:
    name: "{{ java }}"
  default-jre:
    name: default-jre
  gnupg2:
    name: gnupg2
  apt-transport-https:
    name: apt-transport-https
  jenkins:
    name: "jenkins"

jenkins_key_url: "https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key"

jenkins_config_file: "/etc/default/jenkins"

groovy_script_file: "jenkins/files/basic-security.groovy"

groovy_init_dir: "/var/lib/jenkins/init.groovy.d"

jenkins_cli_url: "http://127.0.0.1:8080/jnlpJars/jenkins-cli.jar"

